package com.br.smallmanager.apismallManager.utils;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.FileSystemResource;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import javax.mail.MessagingException;
import javax.mail.internet.MimeMessage;
import java.io.File;

@Service
public class EmailSenderService  {

    @Autowired
    private JavaMailSender mailSender;


    public void sendSimpleEmail(String toEmail,
                                String body,
                                String subject) {
        SimpleMailMessage message = new SimpleMailMessage();

        message.setFrom("contatosmallmanager@gmail.com");
        message.setTo(toEmail);
        message.setText(body);
        message.setSubject(subject);

        mailSender.send(message);
        System.out.println("Mail Send...");
    }

    public void sendEmailWithAttachment(String toEmail,
                                        String body,
                                        String subject,
                                        String attachment) throws MessagingException {

        MimeMessage mimeMessage = mailSender.createMimeMessage();

        MimeMessageHelper mimeMessageHelper
                = new MimeMessageHelper(mimeMessage, true);

        mimeMessageHelper.setFrom("contatosmallmanager@gmail.com");
        mimeMessageHelper.setTo(toEmail);
        mimeMessageHelper.setText(body);
        mimeMessageHelper.setSubject(subject);

        FileSystemResource fileSystem
                = new FileSystemResource(new File(attachment));

        mimeMessageHelper.addAttachment(fileSystem.getFilename(),
                fileSystem);

        mailSender.send(mimeMessage);
        System.out.println("Mail Send...");

    }
    
    public void capturaEmailClient () {
    	
    }
    public void mensagemEmail(String toEmail,
                              String body,
                              String subject,com.br.smallmanager.apismallManager.dto.MensagemDto msg) throws MessagingException {

        MimeMessage mimeMessage = mailSender.createMimeMessage();

        MimeMessageHelper mimeMessageHelper
                = new MimeMessageHelper(mimeMessage, true);

        mimeMessage.setFrom("contatosmallmanager@gmail.com");
        mimeMessageHelper.setTo(toEmail);

        mimeMessageHelper.setSubject(subject);

        String body1 = "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<head>\n"
                + "\n"
                + "  <meta charset=\"utf-8\">\n"
                + "  <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n"
                + "  <title>Password Reset</title>\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                + "  <style type=\"text/css\">\n"
                + "  /**\n"
                + "   * Google webfonts. Recommended to include the .woff version for cross-client compatibility.\n"
                + "   */\n"
                + "  @media screen {\n"
                + "    @font-face {\n"
                + "      font-family: 'Source Sans Pro';\n"
                + "      font-style: normal;\n"
                + "      font-weight: 400;\n"
                + "      src: local('Source Sans Pro Regular'), local('SourceSansPro-Regular'), url(https://fonts.gstatic.com/s/sourcesanspro/v10/ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff) format('woff');\n"
                + "    }\n"
                + "\n"
                + "    @font-face {\n"
                + "      font-family: 'Source Sans Pro';\n"
                + "      font-style: normal;\n"
                + "      font-weight: 700;\n"
                + "      src: local('Source Sans Pro Bold'), local('SourceSansPro-Bold'), url(https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGFkQc6VGVFSmCnC_l7QZG60.woff) format('woff');\n"
                + "    }\n"
                + "  }\n"
                + "\n"
                + "  /**\n"
                + "   * Avoid browser level font resizing.\n"
                + "   * 1. Windows Mobile\n"
                + "   * 2. iOS / OSX\n"
                + "   */\n"
                + "  body,\n"
                + "  table,\n"
                + "  td,\n"
                + "  a {\n"
                + "    -ms-text-size-adjust: 100%; /* 1 */\n"
                + "    -webkit-text-size-adjust: 100%; /* 2 */\n"
                + "  }\n"
                + "\n"
                + "  /**\n"
                + "   * Remove extra space added to tables and cells in Outlook.\n"
                + "   */\n"
                + "  table,\n"
                + "  td {\n"
                + "    mso-table-rspace: 0pt;\n"
                + "    mso-table-lspace: 0pt;\n"
                + "  }\n"
                + "\n"
                + "  /**\n"
                + "   * Better fluid images in Internet Explorer.\n"
                + "   */\n"
                + "  img {\n"
                + "    -ms-interpolation-mode: bicubic;\n"
                + "  }\n"
                + "\n"
                + "  /**\n"
                + "   * Remove blue links for iOS devices.\n"
                + "   */\n"
                + "  a[x-apple-data-detectors] {\n"
                + "    font-family: inherit !important;\n"
                + "    font-size: inherit !important;\n"
                + "    font-weight: inherit !important;\n"
                + "    line-height: inherit !important;\n"
                + "    color: inherit !important;\n"
                + "    text-decoration: none !important;\n"
                + "  }\n"
                + "\n"
                + "  /**\n"
                + "   * Fix centering issues in Android 4.4.\n"
                + "   */\n"
                + "  div[style*=\"margin: 16px 0;\"] {\n"
                + "    margin: 0 !important;\n"
                + "  }\n"
                + "\n"
                + "  body {\n"
                + "    width: 100% !important;\n"
                + "    height: 100% !important;\n"
                + "    padding: 0 !important;\n"
                + "    margin: 0 !important;\n"
                + "  }\n"
                + "\n"
                + "  /**\n"
                + "   * Collapse table borders to avoid space between cells.\n"
                + "   */\n"
                + "  table {\n"
                + "    border-collapse: collapse !important;\n"
                + "  }\n"
                + "\n"
                + "  a {\n"
                + "    color: #ffff;\n"
                + "  }\n"
                + "\n"
                + "  img {\n"
                + "    height: auto;\n"
                + "    line-height: 100%;\n"
                + "    text-decoration: none;\n"
                + "    border: 0;\n"
                + "    outline: none;\n"
                + "  }\n"
                + "  </style>\n"
                + "\n"
                + "</head>\n"
                + "<body style=\"background-color: #ffff;\">\n"
                + "\n"
                + "  <!-- start preheader -->\n"
                + "  <div class=\"preheader\" style=\"display: none; max-width: 0; max-height: 0; overflow: hidden; font-size: 1px; line-height: 1px; color: #fff; opacity: 0;\">\n"
                + "    A preheader is the short summary text that follows the subject line when an email is viewed in the inbox.\n"
                + "  </div>\n"
                + "  <!-- end preheader -->\n"
                + "\n"
                + "  <!-- start body -->\n"
                + "  <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
                + "\n"
                + "    <!-- start logo -->\n"
                + "    <tr>\n"
                + "      <td align=\"center\" bgcolor=\"#fff\">\n"
                + "        <!--[if (gte mso 9)|(IE)]>\n"
                + "        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">\n"
                + "        <tr>\n"
                + "        <td align=\"center\" valign=\"top\" width=\"600\">\n"
                + "        <![endif]-->\n"
                + "        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\n"
                + "          <tr>\n"
                + "            <td align=\"center\" valign=\"top\" style=\"padding: 36px 24px;\">\n"
                + "              <a href=\"https://sendgrid.com\" target=\"_blank\" style=\"display: inline-block;\">\n"
                + "                <img src="+msg.getLogo()+" alt=\"Logo\" border=\"0\" width=\"100\" style=\"display: block; width: 100px; max-width: 100px; min-width: 100px;\">\n"
                + "              </a>\n"
                + "            </td>\n"
                + "          </tr>\n"
                + "        </table>\n"
                + "        <!--[if (gte mso 9)|(IE)]>\n"
                + "        </td>\n"
                + "        </tr>\n"
                + "        </table>\n"
                + "        <![endif]-->\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "    <!-- end logo -->\n"
                + "\n"
                + "    <!-- start hero -->\n"
                + "    <tr>\n"
                + "      <td align=\"center\" bgcolor=\"#fff\">\n"
                + "        <!--[if (gte mso 9)|(IE)]>\n"
                + "        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">\n"
                + "        <tr>\n"
                + "        <td align=\"center\" valign=\"top\" width=\"600\">\n"
                + "        <![endif]-->\n"
                + "        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\n"
                + "          <tr>\n"
                + "            <td align=\"left\" bgcolor=\"#ffffff\" style=\"padding: 36px 24px 0; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; border-top: 3px solid #aa00ff;\">\n"
                + "              <h1 style=\"margin: 0; font-size: 32px; font-weight: 700; letter-spacing: -1px; line-height: 48px;\">"+msg.getNome()+" enviou uma Mensagem</h1>\n"
                + "            </td>\n"
                + "          </tr>\n"
                + "        </table>\n"
                + "        <!--[if (gte mso 9)|(IE)]>\n"
                + "        </td>\n"
                + "        </tr>\n"
                + "        </table>\n"
                + "        <![endif]-->\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "    <!-- end hero -->\n"
                + "\n"
                + "    <!-- start copy block -->\n"
                + "    <tr>\n"
                + "      <td align=\"center\" bgcolor=\"#fff\">\n"
                + "      \n"
                + "        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\n"
                + "\n"
                + "          <!-- start copy -->\n"
                + "          <tr>\n"
                + "            <td align=\"left\" bgcolor=\"#ffffff\" style=\"padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;\">\n"
                + "              <p style=\"margin: 0;\">"+msg.getMensagem()+"</p>\n"
                + "            </td>\n"
                + "          </tr>\n"
                + "          <!-- end copy -->\n"
                + "\n"
                + "          <!-- start button -->\n"
                + "          <tr>\n"
                + "            <td align=\"left\" bgcolor=\"#ffffff\">\n"
                + "              <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
                + "                <tr>\n"
                + "                  <td align=\"center\" bgcolor=\"#ffffff\" style=\"padding: 12px;\">\n"
                + "                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "                      <tr>\n"
                + "                         \n"
                + "                      </tr>\n"
                + "                    </table>\n"
                + "                  </td>\n"
                + "                </tr>\n"
                + "              </table>\n"
                + "            </td>\n"
                + "          </tr>\n"
                + "          <!-- end button -->\n"
                + "\n"
                + "          <!-- start copy -->\n"
                + "          <tr>\n"
                + "            <td align=\"left\" bgcolor=\"#ffffff\" style=\"padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;\">\n"
                + "                          </td>\n"
                + "          </tr>\n"
                + "          <!-- end copy -->\n"
                + "\n"
                + "          <!-- start copy -->\n"
                + "          <tr>\n"
                + "            <td align=\"left\" bgcolor=\"#ffffff\" style=\"padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px; border-bottom: 3px solid #d4dadf\">\n"
                + "              <p style=\"margin: 0;\"Animal-X</p>\n"
                + "            </td>\n"
                + "          </tr>\n"
                + "          <!-- end copy -->\n"
                + "\n"
                + "        </table>\n"
                + "        \n"
                + "      </td>\n"
                + "    </tr>\n"
                + "    <!-- end copy block -->\n"
                + "\n"
                + "   \n"
                + "    <!-- end footer -->\n"
                + "\n"
                + "  </table>\n"
                + "  <!-- end body -->\n"
                + "\n"
                + "</body>\n"
                + "</html>";

        mimeMessageHelper.setText(body1,true);
        mimeMessageHelper.setSubject(subject);
        mailSender.send(mimeMessage);

    }
    
    public void sendEmailWithAttachment(String toEmail,
            String body,
            String subject) throws MessagingException {

        MimeMessage mimeMessage = mailSender.createMimeMessage();

        MimeMessageHelper mimeMessageHelper
                = new MimeMessageHelper(mimeMessage, true);

        mimeMessage.setFrom("contatosmallmanager@gmail.com");
        mimeMessageHelper.setTo(toEmail);
        
        mimeMessageHelper.setSubject(subject);
        
        String body1 = "<!DOCTYPE html>\n"
        		+ "<html>\n"
        		+ "<head>\n"
        		+ "\n"
        		+ "  <meta charset=\"utf-8\">\n"
        		+ "  <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n"
        		+ "  <title>Password Reset</title>\n"
        		+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        		+ "  <style type=\"text/css\">\n"
        		+ "  /**\n"
        		+ "   * Google webfonts. Recommended to include the .woff version for cross-client compatibility.\n"
        		+ "   */\n"
        		+ "  @media screen {\n"
        		+ "    @font-face {\n"
        		+ "      font-family: 'Source Sans Pro';\n"
        		+ "      font-style: normal;\n"
        		+ "      font-weight: 400;\n"
        		+ "      src: local('Source Sans Pro Regular'), local('SourceSansPro-Regular'), url(https://fonts.gstatic.com/s/sourcesanspro/v10/ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff) format('woff');\n"
        		+ "    }\n"
        		+ "\n"
        		+ "    @font-face {\n"
        		+ "      font-family: 'Source Sans Pro';\n"
        		+ "      font-style: normal;\n"
        		+ "      font-weight: 700;\n"
        		+ "      src: local('Source Sans Pro Bold'), local('SourceSansPro-Bold'), url(https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGFkQc6VGVFSmCnC_l7QZG60.woff) format('woff');\n"
        		+ "    }\n"
        		+ "  }\n"
        		+ "\n"
        		+ "  /**\n"
        		+ "   * Avoid browser level font resizing.\n"
        		+ "   * 1. Windows Mobile\n"
        		+ "   * 2. iOS / OSX\n"
        		+ "   */\n"
        		+ "  body,\n"
        		+ "  table,\n"
        		+ "  td,\n"
        		+ "  a {\n"
        		+ "    -ms-text-size-adjust: 100%; /* 1 */\n"
        		+ "    -webkit-text-size-adjust: 100%; /* 2 */\n"
        		+ "  }\n"
        		+ "\n"
        		+ "  /**\n"
        		+ "   * Remove extra space added to tables and cells in Outlook.\n"
        		+ "   */\n"
        		+ "  table,\n"
        		+ "  td {\n"
        		+ "    mso-table-rspace: 0pt;\n"
        		+ "    mso-table-lspace: 0pt;\n"
        		+ "  }\n"
        		+ "\n"
        		+ "  /**\n"
        		+ "   * Better fluid images in Internet Explorer.\n"
        		+ "   */\n"
        		+ "  img {\n"
        		+ "    -ms-interpolation-mode: bicubic;\n"
        		+ "  }\n"
        		+ "\n"
        		+ "  /**\n"
        		+ "   * Remove blue links for iOS devices.\n"
        		+ "   */\n"
        		+ "  a[x-apple-data-detectors] {\n"
        		+ "    font-family: inherit !important;\n"
        		+ "    font-size: inherit !important;\n"
        		+ "    font-weight: inherit !important;\n"
        		+ "    line-height: inherit !important;\n"
        		+ "    color: inherit !important;\n"
        		+ "    text-decoration: none !important;\n"
        		+ "  }\n"
        		+ "\n"
        		+ "  /**\n"
        		+ "   * Fix centering issues in Android 4.4.\n"
        		+ "   */\n"
        		+ "  div[style*=\"margin: 16px 0;\"] {\n"
        		+ "    margin: 0 !important;\n"
        		+ "  }\n"
        		+ "\n"
        		+ "  body {\n"
        		+ "    width: 100% !important;\n"
        		+ "    height: 100% !important;\n"
        		+ "    padding: 0 !important;\n"
        		+ "    margin: 0 !important;\n"
        		+ "  }\n"
        		+ "\n"
        		+ "  /**\n"
        		+ "   * Collapse table borders to avoid space between cells.\n"
        		+ "   */\n"
        		+ "  table {\n"
        		+ "    border-collapse: collapse !important;\n"
        		+ "  }\n"
        		+ "\n"
        		+ "  a {\n"
        		+ "    color: #1a82e2;\n"
        		+ "  }\n"
        		+ "\n"
        		+ "  img {\n"
        		+ "    height: auto;\n"
        		+ "    line-height: 100%;\n"
        		+ "    text-decoration: none;\n"
        		+ "    border: 0;\n"
        		+ "    outline: none;\n"
        		+ "  }\n"
        		+ "  </style>\n"
        		+ "\n"
        		+ "</head>\n"
        		+ "<body style=\"background-color: #e9ecef;\">\n"
        		+ "\n"
        		+ "  <!-- start preheader -->\n"
        		+ "  <div class=\"preheader\" style=\"display: none; max-width: 0; max-height: 0; overflow: hidden; font-size: 1px; line-height: 1px; color: #fff; opacity: 0;\">\n"
        		
        		+ "  </div>\n"
        		+ "  <!-- end preheader -->\n"
        		+ "\n"
        		+ "  <!-- start body -->\n"
        		+ "  <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
        		+ "\n"
        		+ "    <!-- start logo -->\n"
        		+ "    <tr>\n"
        		+ "      <td align=\"center\" bgcolor=\"#e9ecef\">\n"
        		+ "        <!--[if (gte mso 9)|(IE)]>\n"
        		+ "        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">\n"
        		+ "        <tr>\n"
        		+ "        <td align=\"center\" valign=\"top\" width=\"600\">\n"
        		+ "        <![endif]-->\n"
        		+ "        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\n"
        		+ "          <tr>\n"
        		+ "            <td align=\"center\" valign=\"top\" style=\"padding: 36px 24px;\">\n"
        		+ "              <a href=\"https://sendgrid.com\" target=\"_blank\" style=\"display: inline-block;\">\n"
        		+ "                <img src=https://photoanimalx.s3.us-east-2.amazonaws.com/LOGOANIMALX-NOME.png alt=\"Logo\" border=\"0\" width=\"70\" style=\"display: block; width: 110px; max-width: 70px; min-width: 110px;\">\n"
        		+ "              </a>\n"
        		+ "            </td>\n"
        		+ "          </tr>\n"
        		+ "        </table>\n"
        		+ "        <!--[if (gte mso 9)|(IE)]>\n"
        		+ "        </td>\n"
        		+ "        </tr>\n"
        		+ "        </table>\n"
        		+ "        <![endif]-->\n"
        		+ "      </td>\n"
        		+ "    </tr>\n"
        		+ "    <!-- end logo -->\n"
        		+ "\n"
        		+ "    <!-- start hero -->\n"
        		+ "    <tr>\n"
        		+ "      <td align=\"center\" bgcolor=\"#e9ecef\">\n"
        		+ "        <!--[if (gte mso 9)|(IE)]>\n"
        		+ "        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">\n"
        		+ "        <tr>\n"
        		+ "        <td align=\"center\" valign=\"top\" width=\"600\">\n"
        		+ "        <![endif]-->\n"
        		+ "        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\n"
        		+ "          <tr>\n"
        		+ "            <td align=\"left\" bgcolor=\"#ffffff\" style=\"padding: 36px 24px 0; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; border-top: 3px solid #EF8800;\">\n"
        		+ "              <h1 style=\"margin: 0; font-size: 32px; font-weight: 700; letter-spacing: -1px; line-height: 48px;\">Redefina sua senha</h1>\n"
        		+ "            </td>\n"
        		+ "          </tr>\n"
        		+ "        </table>\n"
        		+ "        <!--[if (gte mso 9)|(IE)]>\n"
        		+ "        </td>\n"
        		+ "        </tr>\n"
        		+ "        </table>\n"
        		+ "        <![endif]-->\n"
        		+ "      </td>\n"
        		+ "    </tr>\n"
        		+ "    <!-- end hero -->\n"
        		+ "\n"
        		+ "    <!-- start copy block -->\n"
        		+ "    <tr>\n"
        		+ "      <td align=\"center\" bgcolor=\"#e9ecef\">\n"
        		+ "      \n"
        		+ "        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\n"
        		+ "\n"
        		+ "          <!-- start copy -->\n"
        		+ "          <tr>\n"
        		+ "            <td align=\"left\" bgcolor=\"#ffffff\" style=\"padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;\">\n"
        		+ "              <p style=\"margin: 0; font-weight:400\" >Toque no botão abaixo para redefinir a senha da sua conta de cliente. Se você não solicitou uma nova senha, você pode excluir este e-mail com segurança.</p>\n"
        		+ "            </td>\n"
        		+ "          </tr>\n"
        		+ "          <!-- end copy -->\n"
        		+ "\n"
        		+ "          <!-- start button -->\n"
        		+ "          <tr>\n"
        		+ "            <td align=\"left\" bgcolor=\"#ffffff\">\n"
        		+ "              <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
        		+ "                <tr>\n"
        		+ "                  <td align=\"center\" bgcolor=\"#ffffff\" style=\"padding: 12px;\">\n"
        		+ "                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
        		+ "                      <tr>\n"
        		+ "                        <td align=\"center\" bgcolor=\"#EF8800\" style=\"border-radius: 6px;\">\n"
        		+ "                          <a href=\""+body+" target=\"_blank\" style=\"display: inline-block; padding: 16px 36px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; color:black; text-decoration: none; border-radius: 6px;\">Redefinir minha senha</a>\n"
        		+ "                        </td>\n"
        		+ "                      </tr>\n"
        		+ "                    </table>\n"
        		+ "                  </td>\n"
        		+ "                </tr>\n"
        		+ "              </table>\n"
        		+ "            </td>\n"
        		+ "          </tr>\n"
        		+ "          <!-- end button -->\n"
        		+ "\n"
        		+ "          <!-- start copy -->\n"
        		+ "          <tr>\n"
        		+ "            <td align=\"left\" bgcolor=\"#ffffff\" style=\"padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;\">\n"
        		+ "              <p style=\"margin: 0;\">Se isso não funcionar, copie e cole o seguinte link no seu navegador:</p>\n"
        		+ "              <p style=\"margin: 0;\"><a href=\"" +body +"target=\"_blank\">"+body+"</a></p>\n"
        		+ "            </td>\n"
        		+ "          </tr>\n"
        		+ "          <!-- end copy -->\n"
        		+ "\n"
        		+ "          <!-- start copy -->\n"
        		+ "          <tr>\n"
        		+ "            <td align=\"left\" bgcolor=\"#ffffff\" style=\"padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px; border-bottom: 3px solid #d4dadf\">\n"
        		+ "              <p style=\"margin: 0;\"Animal-X</p>\n"
        		+ "            </td>\n"
        		+ "          </tr>\n"
        		+ "          <!-- end copy -->\n"
        		+ "\n"
        		+ "        </table>\n"
        		+ "        <!--[if (gte mso 9)|(IE)]>\n"
        		+ "        </td>\n"
        		+ "        </tr>\n"
        		+ "        </table>\n"
        		+ "        <![endif]-->\n"
        		+ "      </td>\n"
        		+ "    </tr>\n"
        		+ "    <!-- end copy block -->\n"
        		+ "\n"
        		+ "    <!-- start footer -->\n"
        		+ "    <tr>\n"
        		+ "      <td align=\"center\" bgcolor=\"#e9ecef\" style=\"padding: 24px;\">\n"
        		+ "        <!--[if (gte mso 9)|(IE)]>\n"
        		+ "        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">\n"
        		+ "        <tr>\n"
        		+ "        <td align=\"center\" valign=\"top\" width=\"600\">\n"
        		+ "        <![endif]-->\n"
        		+ "        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width: 600px;\">\n"
        		+ "\n"
        		+ "          <!-- start permission -->\n" 
        		+ "          <!-- end permission -->\n" 
        		+ "          <!-- start unsubscribe -->\n" 
        		+ "          <!-- end unsubscribe -->\n"
        		+ "\n"
        		+ "        </table>\n"
        		+ "         \n"
        		+ "      </td>\n"
        		+ "    </tr>\n"
        		+ "    <!-- end footer -->\n"
        		+ "\n"
        		+ "  </table>\n"
        		+ "  <!-- end body -->\n"
        		+ "\n"
        		+ "</body>\n"
        		+ "</html>";
         
        mimeMessageHelper.setText(body1,true); 
        mimeMessageHelper.setSubject(subject); 
        mailSender.send(mimeMessage);  
    }
    

}
